services:
  app_proxy:
    environment:
      APP_HOST: mieldehabanero-umbrel-jellystat_app_1
      APP_PORT: '3000'
  app:
    image: cyfershepard/jellystat:1.1.7
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8a23ad09-61cf-4178-a783-6d4586496e3a
      - POSTGRES_IP=mieldehabanero-umbrel-jellystat_db_1
      - POSTGRES_PORT=5432
      - JWT_SECRET="my-secret-jwt-key"
    volumes:
      - ${APP_DATA_DIR}/data/backup-data:/app/backend/backup-data
  db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: jfstat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8a23ad09-61cf-4178-a783-6d4586496e3a
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
